library(readr)
library(RecordLinkage)
library(stringdist)
library(wordnet)
library(openNLP)
Sys.setenv(WNHOME ="/Users/disha.gupta1@ibm.com/Downloads/WordNet-2.1/dict")
setDict("/Users/disha.gupta1@ibm.com/Downloads/WordNet-2.1/dict")
setwd("/Users/disha.gupta1@ibm.com/Desktop/Quora")
train = read_csv("train_data_dist.csv")
trainlabels=read_csv("train_labels.csv",col_names = F)
colnames(trainlabels)=c("id","is_duplicate")
test = read_csv("test_data_dist.csv")
sample_submission = read_csv("sample_submission.csv")

train$CommonPC=apply(train, 1, function(x) common(x[2],x[3]))/apply(train, 1, function(x) all(x[2],x[3]))
train$DiffPC=apply(train, 1, function(x) diff(x[2],x[3]))/apply(train, 1, function(x) all(x[2],x[3]))
test$CommonPC=common(test[,2],test[,3])/all(test[,2],test[,3])
test$DiffPC=diff(test[,2],train[,3])/all(test[,2],test[,3])

train=merge(train,trainlabels,by="id")
write_csv(train,"train_data_dist_addfeatures.csv")
write_csv(test,"test_data_dist_addfeatures.csv")
